language: java
install: true

jdk:
- oraclejdk8

script:
- ./gradlew build

before_install:
- openssl aes-256-cbc -K $encrypted_359d499a487e_key -iv $encrypted_359d499a487e_iv -in src/main/resources/application.yml.enc -out src/main/resources/application.yml -d
